
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOAT_LIT = 53;
  public static final int CHAR_LIT = 56;
  public static final int WHEN = 10;
  public static final int SHOW = 14;
  public static final int MULT = 27;
  public static final int CHAR = 23;
  public static final int DIFERENTE = 39;
  public static final int CORCHETE_DER = 48;
  public static final int INT = 20;
  public static final int FOR = 11;
  public static final int LLAVE_IZQ = 45;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int ENDL = 19;
  public static final int DECIDE = 4;
  public static final int COAL = 18;
  public static final int OR = 41;
  public static final int GET = 15;
  public static final int NAVIDAD = 17;
  public static final int PAREN_DER = 44;
  public static final int DIV = 28;
  public static final int INCREMENTO = 32;
  public static final int LOOP = 8;
  public static final int EXIT = 9;
  public static final int ID = 54;
  public static final int IGUAL_IGUAL = 38;
  public static final int OF = 5;
  public static final int EOF = 0;
  public static final int BOOLEAN = 22;
  public static final int DIV_ENTERA = 29;
  public static final int RETURN = 12;
  public static final int DECREMENTO = 33;
  public static final int error = 1;
  public static final int COMA = 50;
  public static final int MODULO = 30;
  public static final int MENOS = 26;
  public static final int MENOR = 34;
  public static final int BREAK = 13;
  public static final int WORLD = 2;
  public static final int ASIGNACION = 51;
  public static final int MAYOR = 36;
  public static final int POTENCIA = 31;
  public static final int FLECHA = 49;
  public static final int ELSE = 6;
  public static final int LLAVE_DER = 46;
  public static final int CORCHETE_IZQ = 47;
  public static final int MAYOR_IGUAL = 37;
  public static final int FLOAT = 21;
  public static final int BOOL_LIT = 57;
  public static final int END = 7;
  public static final int STRING = 24;
  public static final int LOCAL = 3;
  public static final int MENOR_IGUAL = 35;
  public static final int STRING_LIT = 55;
  public static final int INT_LIT = 52;
  public static final int PAREN_IZQ = 43;
  public static final int GIFT = 16;
  public static final int MAS = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WORLD",
  "LOCAL",
  "DECIDE",
  "OF",
  "ELSE",
  "END",
  "LOOP",
  "EXIT",
  "WHEN",
  "FOR",
  "RETURN",
  "BREAK",
  "SHOW",
  "GET",
  "GIFT",
  "NAVIDAD",
  "COAL",
  "ENDL",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "DIV_ENTERA",
  "MODULO",
  "POTENCIA",
  "INCREMENTO",
  "DECREMENTO",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "AND",
  "OR",
  "NOT",
  "PAREN_IZQ",
  "PAREN_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "FLECHA",
  "COMA",
  "ASIGNACION",
  "INT_LIT",
  "FLOAT_LIT",
  "ID",
  "STRING_LIT",
  "CHAR_LIT",
  "BOOL_LIT"
  };
}

